.gitignore
README.md
integration/config/local.conf.js
integration/config/sauce.conf.js
integration/config/wdio.conf.js
integration/tests/frontpage.test.js
package.json
src/middlewares/__tests__/logger.middleware.test.js
test.env
wallaby.config.js

Setup basic application

---

.eslintrc
.gitignore
package.json
src/app.js
src/client/components/uploadForm/imageUpload.component.js
src/client/components/uploadForm/previewContainer.component.js
src/client/components/uploadForm/uploadFormContainer.component.js
src/client/index.js
src/routes/root.routes.js
webpack.config.js

Add image upload form

---

.bithoundrc
README.md
package.json
src/app.js
src/services/smaug/smaug.client.js
src/utils/__tests__/config.util.test.js
src/utils/config.util.js
src/utils/request.util.js
src/utils/sanityCheck.util.js
test.env

Smaug client

---

package.json
src/app.js
src/services/serviceprovider/serviceprovider.client.js
src/services/smaug/smaug.client.js
src/utils/config.util.js
src/utils/request.util.js
test.env

Service Provider client

---

src/utils/__tests__/validateId.util.test.js
src/utils/validateId.util.js
wallaby.config.js

methods for extracting and validating id from urls and files

---

src/client/components/topbar/topbar.component.js
src/client/scss/components/topbar.scss
src/client/scss/index.scss

Styling logout button

---

.gitignore
integration/config/wdio.conf.js
integration/pages/upload.page.js
integration/tests/imageupload.test.js
integration/tests/login-out.test.js
integration/tests/urlupload.test.js
integration/tests/workInfo.test.js
package.json

Integrationstests skal køres på CI miljøet (ux-is.dbc.dk)

---

integration/config/jenkins.conf.js
integration/config/wdio.conf.js
package.json

Added Jenkins command

---

package.json

removed koa-pug

---

integration/tests/urlupload.test.js
src/client/components/preview/previewContainer.component.js
src/client/state/stateElements.js
src/routes/index.routes.js
src/services/serviceprovider/serviceprovider.client.js
src/utils/validateObject.util.js

Upload urls to moreinfo update

---

integration/tests/workInfo.test.js
package.json
src/client/components/login/loginForm.component.js
src/client/components/preview/previewContainer.component.js
src/client/components/preview/previewError.component.js
src/client/components/preview/previewList.component.js
src/client/components/preview/previewStatus.component.js
src/client/components/upload/uploadContainer.component.js
src/client/scss/components/button.scss
src/client/scss/components/icons.scss
src/client/scss/components/id-form.scss
src/client/scss/components/login-form.scss
src/client/scss/components/messages.scss
src/client/scss/components/preview.scss
src/client/scss/components/status.scss
src/client/scss/components/upload-button.scss
src/client/scss/config/config.scss
src/client/scss/globals/forms.scss
src/client/scss/globals/load-svg.scss
src/client/scss/globals/resets.scss
src/client/scss/index.scss
src/client/scss/svg/upload.svg
src/client/state/state.js

Design adjustments step 2

---

package.json

undo update extract-text-webpack-plugin. version 2 requires webpack 2

---

integration/pages/upload.page.js
integration/tests/imageupload.test.js
integration/utils/browser.util.js
src/client/components/preview/previewError.component.js
src/client/components/preview/previewId.component.js
src/client/components/preview/previewList.component.js
src/client/components/upload/imageUpload.component.js
src/client/components/upload/uploadContainer.component.js
src/client/components/upload/uploadTypePicker.component.js
src/client/components/upload/urlUpload.component.js
src/client/state/state.js
src/client/state/stateElements.js
src/utils/__tests__/splitString.util.test.js
src/utils/splitString.util.js

Fixes various issues

---

integration/pages/upload.page.js
integration/tests/workInfo.test.js
src/client/components/overlay/overlay.component.js
src/client/components/preview/previewError.component.js
src/client/components/preview/previewId.component.js
src/client/components/preview/previewList.component.js
src/client/components/upload/uploadContainer.component.js
src/client/scss/components/preview.scss
src/client/state/state.js

Styling and text edits

---

integration/pages/upload.page.js
src/client/components/preview/previewError.component.js
src/client/components/upload/uploadContainer.component.js
src/client/scss/components/id-form.scss
src/client/scss/components/preview.scss
src/services/moreinfoUpdate/moreinfoUpdate.client.js

fixes text in input field

---

src/client/scss/globals/resets.scss
src/routes/index.routes.js
test.env

Added terms and conditions page

---

src/services/serviceprovider/serviceprovider.client.js

Check if values exists in work object

---

src/client/components/preview/previewError.component.js
src/client/components/upload/uploadContainer.component.js
src/client/index.js
src/routes/index.routes.js
src/utils/config.util.js
src/utils/template.util.js
test.env

Add max file size as env variable

---

package.json
src/client/components/login/loginForm.component.js
webpack.config.js

Support for object assign in ie11

---

integration/config/sauce.conf.js
integration/config/wdio.conf.js
integration/pages/upload.page.js
integration/tests/imageupload.test.js
integration/tests/urlupload.test.js
integration/tests/workInfo.test.js

* Removed concurrency
* Adjust timeout
* Better handling of alerts

Update tests to hopefully get more stability against saucelabs.

---

package.json

downgrade wdio-sauce-service to 0.4.0

---

src/services/moreinfoUpdate/moreinfoUpdate.client.js

remove files from /tmp after usage

---

README.md
src/session/store.session.js
src/utils/config.util.js

Solves [UFO-167]
[UFO-167]: https://dbcjira.atlassian.net/browse/UFO-167

Add support for redis cluster
